version: '3.9'
services:
  app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: nest_app
    ports:
      - "3000:3000"
    networks:
      - devnet

  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devnet

  nexus:
    image: sonatype/nexus3
    container_name: nexus_repo
    volumes:
    - nexus-data:/nexus-data
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
    networks:
      - devnet

  sonarqube:
    image: sonarqube:lts-community
    container_name: sonarqube
    environment:
      - SONAR_JDBC_URL=jdbc:postgresql://db_sonar:5432/sonar
      - SONAR_JDBC_USERNAME=sonar
      - SONAR_JDBC_PASSWORD=sonar
    ports:
      - "8084:9000"
    depends_on:
      - db_sonar
    networks:
      - devnet

  db_sonar:
    image: postgres:15
    container_name: db_sonar
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
      - POSTGRES_DB=sonar
    networks:
      - devnet
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  devnet:
    driver: bridge

volumes:
  jenkins_home:
  gitlab-config:
  gitlab-logs:
  gitlab-data:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data: