version: '3.8'

services:
  jenkins:
    build:
      context: .
      dockerfile: Dockerfile-jenkins
      args:
        DOCKER_GID: ${DOCKER_GID} # Esto lo leeremos del host
    container_name: dockercompose-jenkins
    restart: unless-stopped
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - jenkins_net

volumes:
  jenkins_home:

networks:
  jenkins_net:
    driver: bridge
